name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  NODE_ENV: development

jobs:
  validate:
    name: Validate the changes
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: ğŸ“¦ Init Node, pnpm
        uses: ./.github/workflows/actions/init

      - name: âœ… Run linting
        run: pnpm run lint

      - name: âœ… Run build
        run: pnpm run build
